fine_tune_model:
  # The folder with raw input data for training.
  input_folder: 'Data/train'
  # The folder the output model will be saved in.
  model_output_folder: 'C:/classifyclimbs/models'
  # Output folder for training results.
  results_folder: 'C:/classifyclimbs/results'
  
run_model:
  # Input folder containing the images to be used for predictions in the subfolders.
  model_input_folder: 'C:/classifyclimbs/models'
  # A list of comments about the climb.
  climb_comments: ['There was very little gear on this climb','Well protected', 'Fun climb and very safe']
  
  